---
development:
  sessions:
    default:
      database: squash_development
      hosts:
      - localhost:27017
test:
  sessions:
    default:
      database: squash_test
      hosts:
      - localhost:27017
      options:
        consistency: :strong
        max_retries: 1
        retry_interval: 0
production:
  sessions:
    default:
      database: squash_production
      hosts:
      - localhost:27017
      options:
